# Optional: OpenShift GitOps. See README “Path 2”. Apply into openshift-gitops (or your Argo namespace).
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dr-poc-setup
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/awez-sonde/oadp-virtualization-recovery-iac.git
    targetRevision: main
    path: setup
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-adp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
